name: Run Playlist Generator

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  generate-playlist:
    runs-on: ubuntu-latest  # Use an OS that supports Node.js 20

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  # Force Node.js 20
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true  # Allow use of insecure Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.1  # Checkout the repository

      - name: Set up Bash
        run: |
          # Make your script executable
          chmod +x ./scripts/playlist_generator.sh

      - name: Run Playlist Generator for Multiple Days
        run: |
          # Run the playlist generator for each day of the week
          for day in monday tuesday wednesday thursday friday saturday sunday; do
            echo "Generating playlist for $day..."
            ./scripts/playlist_generator.sh "$day" || { echo "Failed to generate playlist for $day"; exit 1; }
          done
